### ISSUE TITLE
Auto creation of xip.io sub domains break when vsphere cloud-providor is specified

### ISSUE THREAD

**Issue by svagml** [rancher/rke#894]
**RKE version:**
Not sure where to locate RKE version

**Docker version: (`docker version`,`docker info` preferred)**

Docker version:
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64
 Experimental: false

Docker Info:
Containers: 41
 Running: 28
 Paused: 0
 Stopped: 13
Images: 18
Server Version: 17.03.2-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.32-rancher2
Operating System: RancherOS v1.4.0
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.949 GiB
Name: qa-node01
ID: 5GCF:ATAM:LTBQ:X3GC:KEWH:ZK23:NMBV:B4UZ:A2KV:XUFO:TUPD:JC75

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="RancherOS"
VERSION=v1.4.0
ID=rancheros
ID_LIKE=
VERSION_ID=v1.4.0
PRETTY_NAME="RancherOS v1.4.0"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=

4.14.32-rancher2

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vmware
vsphere 6.7
single esxi 6.5

**cluster.yml file:**
addon_job_timeout: 30
authentication: 
  strategy: "x509"
bastion_host: 
  ssh_agent_auth: false
cloud_provider: 
  name: "vsphere"
  vsphereCloudProvider: 
    global: 
      insecure-flag: true
      soap-roundtrip-count: 0
    virtual_center: 
      10.0.0.21: 
        datacenters: "Cybertron"
        password: "password"
        soap-roundtrip-count: 0
        user: "administrator@vsphere.local"
    workspace: 
      datacenter: "Cybertron"
      default-datastore: "P410_SSD_RAID5"
      folder: "/"
      server: "vcenter.transformers.lan"
ignore_docker_version: false
# 
#   # Currently only nginx ingress provider is supported.
#   # To disable ingress controller, set `provider: none`
#   # To enable ingress on specific nodes, use the node_selector, eg:
#      provider: nginx
#      node_selector:
#        app: ingress
# 
ingress: 
  provider: "nginx"
kubernetes_version: "v1.11.1-rancher1-1"
monitoring: 
  provider: "metrics-server"
# 
#   # If you are using calico on AWS
# 
#      network:
#        plugin: calico
#        calico_network_provider:
#          cloud_provider: aws
# 
#   # To specify flannel interface
# 
#      network:
#        plugin: flannel
#        flannel_network_provider:
#          iface: eth1
# 
#   # To specify flannel interface for canal plugin
# 
#      network:
#        plugin: canal
#        canal_network_provider:
#          iface: eth1
# 
network: 
  plugin: "canal"
# 
#      services:
#        kube_api:
#          service_cluster_ip_range: 10.43.0.0/16
#        kube_controller:
#          cluster_cidr: 10.42.0.0/16
#          service_cluster_ip_range: 10.43.0.0/16
#        kubelet:
#          cluster_domain: cluster.local
#          cluster_dns_server: 10.43.0.10
# 
services: 
  etcd: 
    extra_args: 
      election-timeout: "5000"
      heartbeat-interval: "500"
    snapshot: false
  kube-api: 
    pod_security_policy: false
  kubelet: 
    fail_swap_on: false
ssh_agent_auth: false

**Steps to Reproduce:**
Creating or editing a cluster to add vsphere cloud_providor.

**Results:**
Breaks auto creation of xip.io sub domains.  It doesn't break existing apps/workload, after adding the stanza and deploying a new app, no more auto creation.  It appears to still make the discoveries though.

**Comment by svagml** [comment]
Any update on this bug?  Rancher v2.1.0 just came out, was this addressed in new version?

**Comment by alena1108** [comment]
@svagml xip.io domains are being created by rancher, not rke. Can you elaborate on `Breaks auto creation of xip.io sub domains` - you don't see xip io domains being reflected on ingress? or it is reflected, but not resolved? Or you see any errors in the rancher log

**Comment by deniseschannon** [comment]
@svagml  please file a new issue in rancher/rancher if you are still facing issues. 

The issues in RKE are meant to be for the RKE CLI, but if you are having issues in Rancher, please file them in the rancher/rancher repo.
